name : gateway release

on:
  release:
    types: [created]
    paths:
    - 'gateway/**'

jobs:
  
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/m-p/32167#M1027

      - name: Image Tag
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build image
        run: |
          docker build -t ghcr.io/blackstorm/web3-avatar/gateway:${{ steps.tag.outputs.TAG }} .
          docker push ghcr.io/blackstorm/web3-avatar/gateway:${{ steps.tag.outputs.TAG }}
        working-directory: gateway
  
  release:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get version
        id: tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}
      - name: Kube render
        run: |
          kustomize edit set image gateway=ghcr.io/blackstorm/web3-avatar/gateway:${{ steps.tag.outputs.TAG }}
          kustomize build . | sed 's/GITHUB_SECRETS_INFURA_TOKEN/${{ secrets.INFURA_TOKEN}}/g' > 0.yaml
        working-directory: gateway/kube
      - name: Release
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          version: v1.21.0
          command: apply -f ./gateway/kube.yaml
